Feat/add oif summit 2023 proposal scs five releases later
SovereignCloudStack/events pull request #20
Opened 2023-01-09 10:30 UTC by fkr

2023-01-09 15:13 UTC, itrich requested changes

2023-01-09 15:13 UTC, itrich commented on OpenInfraSummit2023/SCS-Five-Releases-later.md
> +Since the project start there have been five releases, released twice a year in
Since the project _started_

2023-01-09 15:13 UTC, itrich commented on OpenInfraSummit2023/SCS-Five-Releases-later.md
> +to create one platform — standardized, built and operated by many. The SCS project
My sugestion: A growing community of more than 20 contributing companies set out to create and ...

2023-01-09 15:13 UTC, itrich commented on OpenInfraSummit2023/SCS-Five-Releases-later.md
> +March and September. In the spirit of public money - public code the project utilizes
PMPC and BMWK should be capitalized as they're titles/names.

2023-01-09 15:13 UTC, itrich commented on OpenInfraSummit2023/SCS-Five-Releases-later.md
> +will feature some insights into what has been easy and what was thougth to be easy but
what was _thought_

2023-01-09 15:13 UTC, itrich commented on OpenInfraSummit2023/SCS-Five-Releases-later.md
> +Sovereign Cloud Stack not only defined standards - but enables CSPs. Let's show how!
not only *defines* standards

2023-01-09 15:13 UTC, itrich commented on OpenInfraSummit2023/SCS-Five-Releases-later.md
> +Aside from sheding some light into the progress of the efforts of the Sovereign
into the progress ~~of the efforts~~ of the Sovereign Cloud Stack

2023-01-09 16:18 UTC, fkr commented on OpenInfraSummit2023/SCS-Five-Releases-later.md
> +to create one platform — standardized, built and operated by many. The SCS project
Can you take a look if what I made out of now, matches your idea?

2023-01-09 16:19 UTC, fkr commented
thanks @itrich for the initial review, please re-check ;)

2023-01-10 12:55 UTC, itrich approved these changes
LGTM! Thank you for incorporating my feedback. The proposal reads very well and interesting!

2023-01-10 13:00 UTC, merged